# Site settings
title: Joel Carr Frontend Developer
email: joel.ben.carr@gmail.com
description: "Joel Carr is working as a Frontend developer based in London. In this site you can see examples of his work."
baseurl: ""
url: "http://joelcarr.github.io"
timezone: europe/london

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['node_modules/', 'npm-debug.log', 'Gruntfile.js', 'package.json', 'assets/imgs_src/']
